on:
  push:
    tags:
      - "v*"

name: Release asset workflow

jobs:
  release-asset:
    name: Release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - name: Get the short tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Install yarn
        run: npm install -g yarn
      
      - name: Install Packages
        run: yarn install
      
      - name: Build project
        run: yarn run build
      
      - name: Create a zip archive
        run: |
          cd dist
          zip -r ../medium-unlimited.zip .
          cd ..
      
      - name: Create a new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          name: ${{ steps.tag.outputs.VERSION }}
          prerelease: false
          draft: false
          files: |
            medium-unlimited.zip
